[config]
schemaVersion = "0.0.1"

[package]
namespace = "nwesterhausen"
name = "DiscordConnector"
versionNumber = "2.2.0"
description = "Connects your Valheim server to a Discord webhook. Works for both dedicated and client-hosted servers."
websiteUrl = "https://discordconnector.valheim.nwest.games/"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2201"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "../bin/DiscordConnector"
target = "./"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]
categories = [
  "hildirs-request-update",
  "utility",
  "server-side",
  "ashlands-update",
]
